/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VyppnHeader {
    }
}
declare global {
    interface HTMLVyppnHeaderElement extends Components.VyppnHeader, HTMLStencilElement {
    }
    var HTMLVyppnHeaderElement: {
        prototype: HTMLVyppnHeaderElement;
        new (): HTMLVyppnHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "vyppn-header": HTMLVyppnHeaderElement;
    }
}
declare namespace LocalJSX {
    interface VyppnHeader {
    }
    interface IntrinsicElements {
        "vyppn-header": VyppnHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vyppn-header": LocalJSX.VyppnHeader & JSXBase.HTMLAttributes<HTMLVyppnHeaderElement>;
        }
    }
}
